### PR TITLE
Update to docs - add details/summary

### PR DESCRIPTION
**Pull request by mdroidian**
added
`<details>` `<summary>` in a few places

Tested manually in `index.mdx` in `roamjs-com`, seemed good.

https://user-images.githubusercontent.com/3792666/215666689-3d3f36a2-fb1d-4101-beac-863e88bca109.mp4

@dvargas92495

### CODE REVIEW

**Comment by dvargas92495** [comment]
What do those elements add?

Does it render correctly in Roam Depot?

**Comment by mdroidian** [comment]
https://github.com/dvargas92495/roamjs-query-builder/pull/28/commits/64cdb03e1ddba76debcaa737b823ac36ba681399 to fix Roam Depot rendering

image

**Comment by dvargas92495** [comment]
> Before the PR I looked to see if any other extension implemented them.

You can test this locally when you load extensions in developer mode

**Comment by mdroidian** [comment]
> > Before the PR I looked to see if any other extension implemented them.
> 
> You can test this locally when you load extensions in developer mode

of course!  🤦‍♂️

Not supported, but doesn't really break either 🤷‍♂️

image

**Comment by dvargas92495** [comment]
let's hold off on this one until Roam responds with updates to handle headings + detail/summaries

**Comment by dvargas92495** [comment]
Does this break anything if it were to merge? if not, let's resolve conflicts and get it in, to clean it out from pending pull requests

**Comment by mdroidian** [comment]
I'd rather just scrap this PR and revisit during next round of doc updates.

**Pull request closed without merging**
